server:
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: cloud-gateway

  cloud:
    gateway:
      server:
        webflux:

          httpclient:
            connect-timeout: 5000
            response-timeout: 30s

          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

          globalcors:
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              "[/**]":
                allowedOrigins:
                  - http://localhost:5173
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - PATCH
                  - OPTIONS
                allowedHeaders:
                  - "*"
                allowCredentials: true

          routes:
            - id: product-service
              uri: ${PRODUCT_SERVICE_URI:http://product-service.spring-product-local:8080}
              predicates:
                - Path=/product/**
              filters:
                - RewritePath=/product/(?<segment>.*), /v1/product/${segment}
            - id: order-service
              uri: ${ORDER_SERVICE_URI:http://order-service.spring-product-local:8080}
              predicates:
                - Path=/order/**
              filters:
                - RewritePath=/order/(?<segment>.*), /v1/order/${segment}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,gateway,mappings,env,configprops

  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
      access: read-only

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: TRACE
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: TRACE
    reactor.netty: DEBUG